esphome:
  name: dryer-sensor
  platform: ESP32
  board: firebeetle32

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dryer-Sensors Fallback Hotspot"
    password: !secret wifi_password

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO25
    temperature:
      name: "Dryer Temperature"
    humidity:
      name: "Dryer Humidity"
    update_interval: 30s
